/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagarRouteImport } from './routes/pagar'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCalendarioRouteImport } from './routes/app/calendario'
import { Route as AppCicloRouteImport } from './routes/app/ciclo'
import { Route as AppCuadernoRouteImport } from './routes/app/cuaderno'
import { Route as AppGuiaRouteImport } from './routes/app/guia'
import { Route as AppHoyRouteImport } from './routes/app/hoy'
import { Route as AppInformeRouteImport } from './routes/app/informe'
import { Route as AppMasRouteImport } from './routes/app/mas'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppPreguntarRouteImport } from './routes/app/preguntar'
import { Route as AppRegistroRouteImport } from './routes/app/registro'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarRoute = PagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppCicloRoute = AppCicloRouteImport.update({
  id: '/ciclo',
  path: '/ciclo',
  getParentRoute: () => AppRoute,
} as any)
const AppCuadernoRoute = AppCuadernoRouteImport.update({
  id: '/cuaderno',
  path: '/cuaderno',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiaRoute = AppGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AppRoute,
} as any)
const AppHoyRoute = AppHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AppRoute,
} as any)
const AppInformeRoute = AppInformeRouteImport.update({
  id: '/informe',
  path: '/informe',
  getParentRoute: () => AppRoute,
} as any)
const AppMasRoute = AppMasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPreguntarRoute = AppPreguntarRouteImport.update({
  id: '/preguntar',
  path: '/preguntar',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistroRoute = AppRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/guia': typeof GuiaRoute
  '/login': typeof LoginRoute
  '/pagar': typeof PagarRoute
  '/pricing': typeof PricingRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/ciclo': typeof AppCicloRoute
  '/app/cuaderno': typeof AppCuadernoRoute
  '/app/guia': typeof AppGuiaRoute
  '/app/hoy': typeof AppHoyRoute
  '/app/informe': typeof AppInformeRoute
  '/app/mas': typeof AppMasRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/preguntar': typeof AppPreguntarRoute
  '/app/registro': typeof AppRegistroRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/guia': typeof GuiaRoute
  '/login': typeof LoginRoute
  '/pagar': typeof PagarRoute
  '/pricing': typeof PricingRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/ciclo': typeof AppCicloRoute
  '/app/cuaderno': typeof AppCuadernoRoute
  '/app/guia': typeof AppGuiaRoute
  '/app/hoy': typeof AppHoyRoute
  '/app/informe': typeof AppInformeRoute
  '/app/mas': typeof AppMasRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/preguntar': typeof AppPreguntarRoute
  '/app/registro': typeof AppRegistroRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/guia': typeof GuiaRoute
  '/login': typeof LoginRoute
  '/pagar': typeof PagarRoute
  '/pricing': typeof PricingRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/ciclo': typeof AppCicloRoute
  '/app/cuaderno': typeof AppCuadernoRoute
  '/app/guia': typeof AppGuiaRoute
  '/app/hoy': typeof AppHoyRoute
  '/app/informe': typeof AppInformeRoute
  '/app/mas': typeof AppMasRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/preguntar': typeof AppPreguntarRoute
  '/app/registro': typeof AppRegistroRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/guia'
    | '/login'
    | '/pagar'
    | '/pricing'
    | '/privacidad'
    | '/terminos'
    | '/app/calendario'
    | '/app/ciclo'
    | '/app/cuaderno'
    | '/app/guia'
    | '/app/hoy'
    | '/app/informe'
    | '/app/mas'
    | '/app/onboarding'
    | '/app/preguntar'
    | '/app/registro'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/guia'
    | '/login'
    | '/pagar'
    | '/pricing'
    | '/privacidad'
    | '/terminos'
    | '/app/calendario'
    | '/app/ciclo'
    | '/app/cuaderno'
    | '/app/guia'
    | '/app/hoy'
    | '/app/informe'
    | '/app/mas'
    | '/app/onboarding'
    | '/app/preguntar'
    | '/app/registro'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/guia'
    | '/login'
    | '/pagar'
    | '/pricing'
    | '/privacidad'
    | '/terminos'
    | '/app/calendario'
    | '/app/ciclo'
    | '/app/cuaderno'
    | '/app/guia'
    | '/app/hoy'
    | '/app/informe'
    | '/app/mas'
    | '/app/onboarding'
    | '/app/preguntar'
    | '/app/registro'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  GuiaRoute: typeof GuiaRoute
  LoginRoute: typeof LoginRoute
  PagarRoute: typeof PagarRoute
  PricingRoute: typeof PricingRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar': {
      id: '/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ciclo': {
      id: '/app/ciclo'
      path: '/ciclo'
      fullPath: '/app/ciclo'
      preLoaderRoute: typeof AppCicloRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cuaderno': {
      id: '/app/cuaderno'
      path: '/cuaderno'
      fullPath: '/app/cuaderno'
      preLoaderRoute: typeof AppCuadernoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guia': {
      id: '/app/guia'
      path: '/guia'
      fullPath: '/app/guia'
      preLoaderRoute: typeof AppGuiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hoy': {
      id: '/app/hoy'
      path: '/hoy'
      fullPath: '/app/hoy'
      preLoaderRoute: typeof AppHoyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/informe': {
      id: '/app/informe'
      path: '/informe'
      fullPath: '/app/informe'
      preLoaderRoute: typeof AppInformeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mas': {
      id: '/app/mas'
      path: '/mas'
      fullPath: '/app/mas'
      preLoaderRoute: typeof AppMasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preguntar': {
      id: '/app/preguntar'
      path: '/preguntar'
      fullPath: '/app/preguntar'
      preLoaderRoute: typeof AppPreguntarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registro': {
      id: '/app/registro'
      path: '/registro'
      fullPath: '/app/registro'
      preLoaderRoute: typeof AppRegistroRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCicloRoute: typeof AppCicloRoute
  AppCuadernoRoute: typeof AppCuadernoRoute
  AppGuiaRoute: typeof AppGuiaRoute
  AppHoyRoute: typeof AppHoyRoute
  AppInformeRoute: typeof AppInformeRoute
  AppMasRoute: typeof AppMasRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPreguntarRoute: typeof AppPreguntarRoute
  AppRegistroRoute: typeof AppRegistroRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppCicloRoute: AppCicloRoute,
  AppCuadernoRoute: AppCuadernoRoute,
  AppGuiaRoute: AppGuiaRoute,
  AppHoyRoute: AppHoyRoute,
  AppInformeRoute: AppInformeRoute,
  AppMasRoute: AppMasRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPreguntarRoute: AppPreguntarRoute,
  AppRegistroRoute: AppRegistroRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  GuiaRoute: GuiaRoute,
  LoginRoute: LoginRoute,
  PagarRoute: PagarRoute,
  PricingRoute: PricingRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
